### PR TITLE
Work w/ latest Aerospike

### PR DESCRIPTION
**Pull request by horte**
* Use latest Aerospike npm package (>= v2.4.x)
* Work with latest Aerospike server (currently v3.12)
* Possible to cache values of zero

### CODE REVIEW

**Comment by augnin** [comment]
Hi @horte 

apologies for the late response. I had a look at your PR and took this opportunity to refactor the code base. can you update your PR if I have missed anything in that?

**Comment by horte** [comment]
Great, does the refactor support setting values of 0? I can't seem to find a test case for it. 
Like https://github.com/augnin/catbox-aerospike/pull/3/files#diff-910eb6f57886ca16c136101fb1699231R70

**Comment by augnin** [comment]
@horte can you submit a separate PR for that test case? I will close this PR

**Comment by augnin** [comment]
closing this PR

**Pull request closed without merging**
